# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Podcast iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Podcast iOS
pod 'Moya', '~> 14.0'
pod 'SDWebImage', '~> 5.0'
pod 'FeedKit', '~> 9.0'
end
